# Generated by Django 3.1.2 on 2021-03-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_auto_20180530_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amount_pending',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='fee_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('pending', 'Pending')], default='paid', max_length=30, verbose_name='Fee Status'),
        ),
    ]
