# Generated by Django 3.1.2 on 2021-03-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_remove_member_amount_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='remaining_amount',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
