# Generated by Django 3.1.2 on 2021-03-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_member_remaining_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='amount',
        ),
        migrations.AlterField(
            model_name='member',
            name='fee_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='paid', max_length=30, verbose_name='Fee Status'),
        ),
        migrations.AlterField(
            model_name='member',
            name='paid_amount',
            field=models.CharField(max_length=30),
        ),
    ]
