# Generated by Django 3.1.2 on 2021-03-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_auto_20210314_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='total_amount',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
